formatter: markdown
header-from: .header.md
footer-from: .footer.md
content: |-

  {{ .Header }}

  {{ include "./.content.md" }}

  {{ .Providers }}

  {{ .Outputs }}

  {{ .Inputs }}  
  
settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
  lockfile: false

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: inject
