formatter: markdown
header-from: .header.md
content: |-
  Any arbitrary text can be placed anywhere in the content

  {{ .Header }}

  {{ .Providers }}

  and they don't even need to be in the default order

  {{ .Outputs }}

  {{ .Inputs }}  
  end
settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
  lockfile: false

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: inject
