---
name: misspell
on:
  push:
    branches:
      - main

jobs:
  misspell:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:runner-latest # image with user 'runner:runner' built on tag 'act-latest'
    steps:
      - uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-check
          filter_mode: nofilter
          level: error
