name: pre-commit-check
# description: ""

inputs:
  pre-commit-config:
    description: ""
    required: true
  base-branch:
    description: ""
    required: false
  token:
    description: ""
    required: false
    default: ${{ github.token }}

on:
  push:
    branches:
      - main

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # checkout repository
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false

      - name: initialize Terraform
        run: terraform init --backend=false

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --config ${{ inputs.pre-commit-config }} ${{ steps.set-option.outputs.option }}

      - name: Push pre-commit fixes
        if: always() # Push changes even when pre-commit fails
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(pre-commit): autofix"

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          DUMMY: dummy
          # many of these are covered by better reviewdog linters below
          SKIP: >-
            terraform_tflint_deep,
            no-commit-to-branch,
            terraform_tflint_nocreds,
            terraform_tfsec
