---
name: pre-commit-check
on:
  push:
    branches:
      - main

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # checkout repository
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false

      - name: initialize Terraform
        run: terraform init --backend=false
      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        env:
          AWS_DEFAULT_REGION: us-east-1
          # many of these are covered by better reviewdog linters below
          SKIP: >-
            terraform_tflint_deep,
            no-commit-to-branch,
            terraform_tflint_nocreds,
            terraform_tfsec
