---
name: pull request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # TODO: #22 add job using https://github.com/reviewdog/action-alex
  pre-commit:
    runs-on: ubuntu-latest
    # container:
    #   image: catthehacker/ubuntu:runner-latest # image with user 'runner:runner' built on tag 'act-latest'
    steps:
      - uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: initialize Terraform
        run: terraform init --backend=false

      - name: pre-commit
        uses: pre-commit/action@v2.0.3
        env:
          DUMMY: dummy
          # many of these are covered by better reviewdog linters below
          SKIP: >-
            terraform_tflint_deep,
            no-commit-to-branch,
            terraform_tflint_nocreds,
            terraform_tfsec

  tflint:
    runs-on: ubuntu-latest
    name: runner / tflint
    container:
      image: catthehacker/ubuntu:runner-latest # image with user 'runner:runner' built on tag 'act-latest'

    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}


      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: added
          flags: --module
          level: error

  tfsec:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:runner-latest # image with user 'runner:runner' built on tag 'act-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init --backend=false

      - name: tfsec
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          filter_mode: added
          level: warning

  misspell:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:runner-latest # image with user 'runner:runner' built on tag 'act-latest'
    steps:
      - uses: actions/checkout@v3

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-check
          filter_mode: added
          level: error

  yamllint:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:runner-latest # image with user 'runner:runner' built on tag 'act-latest'
    steps:
      - uses: actions/checkout@v3
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
          level: error
