name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  VAULT_NAMESPACE: "root"
  VAULT_ADDR: "http://vault:8200"
  VAULT_TOKEN: root

jobs:
  terraform:

    name: 'Terraform'
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:runner-latest # image with user 'runner:runner' built on tag 'act-latest'
    # environment: production

    permissions:
      contents: read
      id-token: write

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        # working-directory: "examples/test"
    services:
      vault:
        image: hashicorp/vault:latest
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_LOG_LEVEL: debug
        options: >-
          --cap-add=IPC_LOCK
      mariadb:
        image: mysql:5.7
        env:
          MYSQL_USER: vault-admin
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wp_vault_test
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Update vault-admin grants
        run: |
          sudo apt update
          sudo apt install mysql-client -y
          mysql --host mariadb -uroot -proot -e "CREATE DATABASE IF NOT EXISTS wp_vault_test;"
          mysql --host mariadb -uroot -proot -e "CREATE USER IF NOT EXISTS 'vault-admin'@'%' IDENTIFIED WITH mysql_native_password BY 'root';"
          mysql --host mariadb -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'vault-admin'@'%' WITH GRANT OPTION;"

      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: "examples/test"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: "examples/test"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: "examples/test"

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
        working-directory: "examples/test"

      - name: Terraform Plan
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: false
        working-directory: "examples/test"

      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        id: secrets
        with:
          url: ${{ env.VAULT_ADDR }}
          method: token
          token: root
          secrets: |
            database/creds/testorg--wp-1 username | USERNAME ;
            database/creds/testorg--wp-1 password | PASSWORD

      - run: echo ${{ steps.secrets.outputs.USERNAME }}
      - run: echo ${{ steps.secrets.outputs.PASSWORD }}
      - name: Check connection to MySql with new user
        run: |
          mysql --host mariadb -u${{ steps.secrets.outputs.USERNAME }} -p${{ steps.secrets.outputs.PASSWORD }} -e "show databases;"
