---
name: Module Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  VAULT_NAMESPACE: "root"
  VAULT_ADDR: http://vault:8200
  VAULT_TOKEN: root
jobs:
  module-test:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:runner-latest

    permissions:
      contents: read  # checkout repository
      id-token: write  # create

    services:
      vault:
        image: hashicorp/vault:latest
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_LOG_LEVEL: debug
        options: >-
          --cap-add=IPC_LOCK
      mariadb:
        image: mysql:5.7
        env:
          MYSQL_USER: vault-admin
          MYSQL_PASSWORD: paSSw0rD
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wp_vault_test
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      # - name: Verify MariaDB connection
      #   env:
      #     PORT: ${{ job.services.mariadb.ports[3306] }}
      #   run: |
      #     while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
      #       sleep 1
      #     done

      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Update vault-admin grants
        run: |
          # mysql --host 127.0.0.1 -uroot -proot -e "CREATE DATABASE wp_vault_test;"
          # mysql --host 127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'vault-admin'@'%' WITH GRANT OPTION;"

      - name: Execute Terraform Plan
        id: test
        run: |
          cd examples/test
          terraform init
          terraform plan
          terraform apply -auto-approve

      - run: echo ${{ steps.test.outputs }}
      - run: echo ${{ steps.test.outputs }}
      - run: echo ${{ steps.test.outputs.stdout }}

      # We've configured pull requests to be allowed to read the
      # secret path "database/creds/ORG-ROLE".
      # We are unable to read "secret/data/main/secret".
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        id: secrets
        with:
          url: http://vault:8200
          method: token
          token: root
          secrets: |
            database/creds/maginfo-wp-1 username | TEST

      # database/creds/testorg-wp_vault_test username | TEST
      # - name: Clear
      #   id: clear
      #   if: always()
      #   run: |
      #     cd examples/test
      #     terraform destroy -auto-approve -refresh=false
